[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements-netlify.txt && mkdir -p ./dist && cp -r ./static ./dist/ && cp -r ./templates ./dist/ && cp _redirects ./dist/"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[dev]
  framework = "#custom"
  command = "python simple_app_serverless.py"
  port = 5050
  targetPort = 5050

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 