[build]
  command = "bash netlify.sh"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  NODE_VERSION = "16"

[dev]
  framework = "#custom"
  command = "python simple_app_serverless.py"
  port = 5050
  targetPort = 5050

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 